import Head from 'next/head';
import { useFetchData } from '../hooks/useFetchData';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import { useState } from 'react';

export default function Home() {
	const [page, setPage] = useState(1);

	const { data, isLoading, error } = useFetchData(
		'https://api.github.com/repos/vercel/swr'
	);

	const {
		data: posts,
		error: postsError,
		isLoading: postsLoading
	} = useFetchData('https://jsonplaceholder.typicode.com/posts', page);

	// if (error || postsError) return 'An error has occurred.';

	if (isLoading || postsLoading) return <p>Loading...</p>;
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>NextJs SWR Usages</h1>
				<br />
				{data && (
					<>
						<h1>{data.name}</h1>
						<p>{data.description}</p>
						<strong>👁 {data.subscribers_count}</strong>{' '}
						<strong>✨ {data.stargazers_count}</strong>{' '}
						<strong>🍴 {data.forks_count}</strong>
					</>
				)}
				<br />

				{posts &&
					posts?.map((post) => (
						<div key={post.id}>
							<Link href={`/post/${post.id}`}>
								<h2>{post.title}</h2>
							</Link>
							<p>{post.body}</p>
						</div>
					))}

				<br />
				<button disabled={page === 1} onClick={() => setPage(page - 1)}>
					Previous
				</button>
				<button style={{ marginLeft: 10 }} onClick={() => setPage(page + 1)}>
					Next
				</button>
			</main>
		</div>
	);
}
